<?php
include "./config/config.php";
?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">       
        <link rel="shortcut icon" href="./images/d_white.png" type="image/x-icon">
        <link rel="stylesheet" href="./css/loaders.css">
        <link rel="stylesheet" href="./css/style.css">
        <link rel="stylesheet" href="./css/responsive.css">
        <script src="js/index.js"></script>
        <script src="js/cart.js"></script>
        <title><?php echo COMPANY_NAME?></title>
    </head>
    <body onload="loader('body-loader')">
        <div id="body-loader" class="loader">
            <div class="site-preloader"></div>
        </div>
        <div class="site-wrapper flexbox col center w-100">
            <?php require_once('./utilities/header.php')?>
            <div class="container policy">
                <div class="policy-heading-big w-100">
                    <h1>Privacy policy</h1>
                </div>
                <h3 class="policy-heading-small">Privacy policy</h3>

                <p class="policy-text">Last Updated : 29/05/2023</p>
                <h4>Introduction</h4>
                <p class="policy-text">
                 Welcome to <?php echo COMPANY_NAME?>.
                </p>
                <p class="policy-text">
                <?php echo COMPANY_NAME?> (“us”, “we”, or “our”) operates <?php echo WEBSITE?> (hereinafter referred to as “Service”).
                </p>

                <p class="policy-text">
                Our Privacy Policy governs your visit to <?php echo WEBSITE?> and explains how we collect, safeguard and disclose information that results from your use of our Service.
                </p>

                <p class="policy-text">
                We use your data to provide and improve Service. By using Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.
                </p>
                <p class="policy-text">
                Our Terms and Conditions (“Terms”) govern all use of our Service and together with the Privacy Policy constitute your agreement with us (“Agreement”). 
                </p>
                <h4>Definitions</h4>
                <p class="policy-text">
                SERVICE means the <?php echo WEBSITE?> website operated by <?php echo COMPANY_NAME?>.
                </p>
                <p class="policy-text">
                    PERSONAL DATA means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).
                </p>
                <p class="policy-text">
                    
                    USAGE DATA is data collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit).
                </p>
                <p class="policy-text">
                    
                    COOKIES are small files stored on your device (computer or mobile device).
                </p>
                <p class="policy-text">
                    
                    DATA CONTROLLER means a natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.
                </p>
                <p class="policy-text">
                    
                    DATA PROCESSORS (OR SERVICE PROVIDERS) means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.
                </p>
                <p class="policy-text">
                    
                    DATA SUBJECT is any living individual who is the subject of Personal Data.
                </p>
                <p class="policy-text">

                THE USER is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.
                </p>
                <h4>Information Collection and Use</h4>
                <p class="policy-text">
                We collect several different types of information for various purposes to provide and improve our Service to you.
                </p>
                <h4>
                Types of Data Collected
                </h4>

                <p class="policy-text">
                While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (“Personal Data”). Personally identifiable information may include, but is not limited to:
                    <ul>
                        <li> Email address</li>
                        <li>First name and last name</li>
                        <li>PHone Number</li>
                        <li>Address, Country, State, Province, ZIP/Postal code, City</li>
                        <li>Cookies and Usage Data</li>
                    </ul>
                </p>
                <p class="policy-text">
                We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link.
                </p>
                <h4>
                Usage Data
                </h4>
                <p class="policy-text">
                    We may also collect information that your browser sends whenever you visit our Service or when you access Service by or through any device (“Usage Data”).
                </p>                    
                <p class="policy-text">
                    This Usage Data may include information such as your computer’s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
                </p>                    
                <p class="policy-text">

                When you access Service with a device, this Usage Data may include information such as the type of device you use, your device unique ID, the IP address of your device, your device operating system, the type of Internet browser you use, unique device identifiers and other diagnostic data.
                </p>
            </div>
            <?php require_once('./utilities/footer.php')?>

        </div>
        <?php require_once('./utilities/cart.php')?>
        <a href="https://wa.me/91<?php echo MOBILE?>" id="wa" class="whatsapp flexbox center">
            <img src="icons/whatsapp.svg" alt="whatsapp logo">
        </a>
        <script>
            function loader(id){
                document.getElementById(id).style.display="none";
            }
        </script>
        <script src="js/index.js"></script>
        <script src="js/cart.js"></script>
    </body>
</html>